require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::DepartmentsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Department. As you add validations to Admin::Department, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all admin_departments as @admin_departments" do
      department = Admin::Department.create! valid_attributes
      get :index
      assigns(:admin_departments).should eq([department])
    end
  end

  describe "GET show" do
    it "assigns the requested department as @department" do
      department = Admin::Department.create! valid_attributes
      get :show, :id => department.id
      assigns(:department).should eq(department)
    end
  end

  describe "GET new" do
    it "assigns a new department as @department" do
      get :new
      assigns(:department).should be_a_new(Admin::Department)
    end
  end

  describe "GET edit" do
    it "assigns the requested department as @department" do
      department = Admin::Department.create! valid_attributes
      get :edit, :id => department.id
      assigns(:department).should eq(department)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Department" do
        expect {
          post :create, :department => valid_attributes
        }.to change(Admin::Department, :count).by(1)
      end

      it "assigns a newly created department as @department" do
        post :create, :department => valid_attributes
        assigns(:department).should be_a(Admin::Department)
        assigns(:department).should be_persisted
      end

      it "redirects to the created department" do
        post :create, :department => valid_attributes
        response.should redirect_to(Admin::Department.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved department as @department" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Department.any_instance.stub(:save).and_return(false)
        post :create, :department => {}
        assigns(:department).should be_a_new(Admin::Department)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Department.any_instance.stub(:save).and_return(false)
        post :create, :department => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested department" do
        department = Admin::Department.create! valid_attributes
        # Assuming there are no other admin_departments in the database, this
        # specifies that the Admin::Department created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Department.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => department.id, :department => {'these' => 'params'}
      end

      it "assigns the requested department as @department" do
        department = Admin::Department.create! valid_attributes
        put :update, :id => department.id, :department => valid_attributes
        assigns(:department).should eq(department)
      end

      it "redirects to the department" do
        department = Admin::Department.create! valid_attributes
        put :update, :id => department.id, :department => valid_attributes
        response.should redirect_to(department)
      end
    end

    describe "with invalid params" do
      it "assigns the department as @department" do
        department = Admin::Department.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Department.any_instance.stub(:save).and_return(false)
        put :update, :id => department.id, :department => {}
        assigns(:department).should eq(department)
      end

      it "re-renders the 'edit' template" do
        department = Admin::Department.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Department.any_instance.stub(:save).and_return(false)
        put :update, :id => department.id, :department => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested department" do
      department = Admin::Department.create! valid_attributes
      expect {
        delete :destroy, :id => department.id
      }.to change(Admin::Department, :count).by(-1)
    end

    it "redirects to the admin_departments list" do
      department = Admin::Department.create! valid_attributes
      delete :destroy, :id => department.id
      response.should redirect_to(admin_departments_url)
    end
  end

end
